### ISSUE TITLE
Support for debian packages

### ISSUE THREAD

**Issue by adipascu** [resin-io-projects/resin-wpe#14]
I'd like to use this resin-wpe together with node.js.
How can this be done currently?

Support for Debian packages could be a neat way to resolve this issue.

**Comment by ThinhPhan** [comment]
Yes, me too. I start a small backend for WPE to display local HTML file. The problem is there is no Node.js or NPM. How can I install Nodejs and build it with your image? Thank you.

**Comment by adipascu** [comment]
@ThinhPhan resin.io now supports multiplr containers running at the same
time. You vould run this image side by side with Debian and comunicate over
a TCP socket (websockets/http or something else)

**Comment by petrosagg** [comment]
Indeed resin now supports multicontainer and this is the recommended way of using WPE with other packages. You can take a look at this project for how to do it https://github.com/resin-io-projects/multicontainer-demo-rpi3/blob/master/docker-compose.yml#L18-L26
