### ISSUE TITLE
 Failed to update application  HTTP code 500

### ISSUE THREAD

**Issue by ChaiMinChun** [resin-io-projects/resin-wpe#15]
I was getting this error message "Failed to update application due to '(HTTP code 500) servererror - invalid character 'c' looking for beginning of value ; oci runtime error: container_linux.go:263: starting container process caused "exec: \"/wpe-init\": permission denied" while trying to boot up the application. Any idea why this happened? Any help is appreciated. Thank you in advance.

Device: Raspberry pi 3 Model B
Resin OS: 2.10.1+rev1 (prod)

**Comment by ChaiMinChun** [comment]
@petrosagg  no. I just followed the exact steps written in  README.md in this repo

**Comment by petrosagg** [comment]
Are you by any chance using Windows to clone and push this repo and that caused the wpe-init script to lose the executable flag? Or maybe you downloaded as a ZIP and then pushed to resin?

**Comment by ChaiMinChun** [comment]
@petrosagg  Hi, i haven got time to test the latest version. Will test it and let you know after that
