### ISSUE TITLE
 invalid character 'c' looking for beginning of value '

### ISSUE THREAD

**Issue by khinze** [resin-io-projects/resin-wpe#23]
Hi There,

I was quite excited when I saw this project. 

I have just flashed my rasberry pi 3b with Resin OS 2.13.6+rev1.

however as soon as the docker container starts running I am getting the following?

Is there fix for this?

06.08.18 15:11:58 (+0200) Failed to start service 'main sha256:6139867e98af7b8982e8f9ac241cdbcdb74b82bfccfb433dd05bfa9224d38aa1' due to '(HTTP code 500) server error - invalid character 'c' looking for beginning of value '
06.08.18 15:12:28 (+0200) Installing service 'main sha256:6139867e98af7b8982e8f9ac241cdbcdb74b82bfccfb433dd05bfa9224d38aa1'
06.08.18 15:12:28 (+0200) Installed service 'main sha256:6139867e98af7b8982e8f9ac241cdbcdb74b82bfccfb433dd05bfa9224d38aa1'
06.08.18 15:12:28 (+0200) Starting service 'main sha256:6139867e98af7b8982e8f9ac241cdbcdb74b82bfccfb433dd05bfa9224d38aa1'
06.08.18 15:12:29 (+0200) Failed to start service 'main sha256:6139867e98af7b8982e8f9ac241cdbcdb74b82bfccfb433dd05bfa9224d38aa1' due to '(HTTP code 500) server error - invalid character 'c' looking for beginning of value '

**Comment by petrosagg** [comment]
@khinze this looks like a generic error downloading the container from the registry. Try rebooting your device
